// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tmp.IIgYTah7KL

package get

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAttributeRequest) Reset() {
	*x = ProductAttributeRequest{}
	mi := &file_tmp_IIgYTah7KL_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeRequest) ProtoMessage() {}

func (x *ProductAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_IIgYTah7KL_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeRequest.ProtoReflect.Descriptor instead.
func (*ProductAttributeRequest) Descriptor() ([]byte, []int) {
	return file_tmp_IIgYTah7KL_rawDescGZIP(), []int{0}
}

func (x *ProductAttributeRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductAttributeResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Ok            bool                     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ProductId     int32                    `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Attributes    []*AttributeWithCategory `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAttributeResponse) Reset() {
	*x = ProductAttributeResponse{}
	mi := &file_tmp_IIgYTah7KL_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeResponse) ProtoMessage() {}

func (x *ProductAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_IIgYTah7KL_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeResponse.ProtoReflect.Descriptor instead.
func (*ProductAttributeResponse) Descriptor() ([]byte, []int) {
	return file_tmp_IIgYTah7KL_rawDescGZIP(), []int{1}
}

func (x *ProductAttributeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ProductAttributeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProductAttributeResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductAttributeResponse) GetAttributes() []*AttributeWithCategory {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type AttributesCategoriesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductCategoryId []int32                `protobuf:"varint,1,rep,packed,name=product_category_id,json=productCategoryId,proto3" json:"product_category_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttributesCategoriesRequest) Reset() {
	*x = AttributesCategoriesRequest{}
	mi := &file_tmp_IIgYTah7KL_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributesCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributesCategoriesRequest) ProtoMessage() {}

func (x *AttributesCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_IIgYTah7KL_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributesCategoriesRequest.ProtoReflect.Descriptor instead.
func (*AttributesCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_tmp_IIgYTah7KL_rawDescGZIP(), []int{2}
}

func (x *AttributesCategoriesRequest) GetProductCategoryId() []int32 {
	if x != nil {
		return x.ProductCategoryId
	}
	return nil
}

type AttributesCategoriesResponse struct {
	state               protoimpl.MessageState             `protogen:"open.v1"`
	Ok                  bool                               `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error               string                             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AttributeCategories []*AttributeCategoryWithAttributes `protobuf:"bytes,3,rep,name=attribute_categories,json=attributeCategories,proto3" json:"attribute_categories,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttributesCategoriesResponse) Reset() {
	*x = AttributesCategoriesResponse{}
	mi := &file_tmp_IIgYTah7KL_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributesCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributesCategoriesResponse) ProtoMessage() {}

func (x *AttributesCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_IIgYTah7KL_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributesCategoriesResponse.ProtoReflect.Descriptor instead.
func (*AttributesCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_tmp_IIgYTah7KL_rawDescGZIP(), []int{3}
}

func (x *AttributesCategoriesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AttributesCategoriesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AttributesCategoriesResponse) GetAttributeCategories() []*AttributeCategoryWithAttributes {
	if x != nil {
		return x.AttributeCategories
	}
	return nil
}

type ProductsWithCertainAttributesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProductAttributesId []int32                `protobuf:"varint,1,rep,packed,name=product_attributes_id,json=productAttributesId,proto3" json:"product_attributes_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProductsWithCertainAttributesRequest) Reset() {
	*x = ProductsWithCertainAttributesRequest{}
	mi := &file_tmp_IIgYTah7KL_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsWithCertainAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsWithCertainAttributesRequest) ProtoMessage() {}

func (x *ProductsWithCertainAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_IIgYTah7KL_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsWithCertainAttributesRequest.ProtoReflect.Descriptor instead.
func (*ProductsWithCertainAttributesRequest) Descriptor() ([]byte, []int) {
	return file_tmp_IIgYTah7KL_rawDescGZIP(), []int{4}
}

func (x *ProductsWithCertainAttributesRequest) GetProductAttributesId() []int32 {
	if x != nil {
		return x.ProductAttributesId
	}
	return nil
}

type ProductsWithCertainAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ProductIds    []int32                `protobuf:"varint,3,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsWithCertainAttributesResponse) Reset() {
	*x = ProductsWithCertainAttributesResponse{}
	mi := &file_tmp_IIgYTah7KL_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsWithCertainAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsWithCertainAttributesResponse) ProtoMessage() {}

func (x *ProductsWithCertainAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_IIgYTah7KL_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsWithCertainAttributesResponse.ProtoReflect.Descriptor instead.
func (*ProductsWithCertainAttributesResponse) Descriptor() ([]byte, []int) {
	return file_tmp_IIgYTah7KL_rawDescGZIP(), []int{5}
}

func (x *ProductsWithCertainAttributesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ProductsWithCertainAttributesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProductsWithCertainAttributesResponse) GetProductIds() []int32 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type AttributeWithoutCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeWithoutCategory) Reset() {
	*x = AttributeWithoutCategory{}
	mi := &file_tmp_IIgYTah7KL_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeWithoutCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeWithoutCategory) ProtoMessage() {}

func (x *AttributeWithoutCategory) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_IIgYTah7KL_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeWithoutCategory.ProtoReflect.Descriptor instead.
func (*AttributeWithoutCategory) Descriptor() ([]byte, []int) {
	return file_tmp_IIgYTah7KL_rawDescGZIP(), []int{6}
}

func (x *AttributeWithoutCategory) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttributeWithoutCategory) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AttributeCategoryWithoutAttributes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductCategoryId int32                  `protobuf:"varint,2,opt,name=product_category_id,json=productCategoryId,proto3" json:"product_category_id,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttributeCategoryWithoutAttributes) Reset() {
	*x = AttributeCategoryWithoutAttributes{}
	mi := &file_tmp_IIgYTah7KL_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeCategoryWithoutAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeCategoryWithoutAttributes) ProtoMessage() {}

func (x *AttributeCategoryWithoutAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_IIgYTah7KL_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeCategoryWithoutAttributes.ProtoReflect.Descriptor instead.
func (*AttributeCategoryWithoutAttributes) Descriptor() ([]byte, []int) {
	return file_tmp_IIgYTah7KL_rawDescGZIP(), []int{7}
}

func (x *AttributeCategoryWithoutAttributes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttributeCategoryWithoutAttributes) GetProductCategoryId() int32 {
	if x != nil {
		return x.ProductCategoryId
	}
	return 0
}

func (x *AttributeCategoryWithoutAttributes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AttributeCategoryWithAttributes struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Id                int32                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductCategoryId int32                       `protobuf:"varint,2,opt,name=product_category_id,json=productCategoryId,proto3" json:"product_category_id,omitempty"`
	Title             string                      `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Attributes        []*AttributeWithoutCategory `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttributeCategoryWithAttributes) Reset() {
	*x = AttributeCategoryWithAttributes{}
	mi := &file_tmp_IIgYTah7KL_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeCategoryWithAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeCategoryWithAttributes) ProtoMessage() {}

func (x *AttributeCategoryWithAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_IIgYTah7KL_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeCategoryWithAttributes.ProtoReflect.Descriptor instead.
func (*AttributeCategoryWithAttributes) Descriptor() ([]byte, []int) {
	return file_tmp_IIgYTah7KL_rawDescGZIP(), []int{8}
}

func (x *AttributeCategoryWithAttributes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttributeCategoryWithAttributes) GetProductCategoryId() int32 {
	if x != nil {
		return x.ProductCategoryId
	}
	return 0
}

func (x *AttributeCategoryWithAttributes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AttributeCategoryWithAttributes) GetAttributes() []*AttributeWithoutCategory {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type AttributeWithCategory struct {
	state             protoimpl.MessageState              `protogen:"open.v1"`
	Title             string                              `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AttributeCategory *AttributeCategoryWithoutAttributes `protobuf:"bytes,3,opt,name=attribute_category,json=attributeCategory,proto3" json:"attribute_category,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttributeWithCategory) Reset() {
	*x = AttributeWithCategory{}
	mi := &file_tmp_IIgYTah7KL_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeWithCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeWithCategory) ProtoMessage() {}

func (x *AttributeWithCategory) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_IIgYTah7KL_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeWithCategory.ProtoReflect.Descriptor instead.
func (*AttributeWithCategory) Descriptor() ([]byte, []int) {
	return file_tmp_IIgYTah7KL_rawDescGZIP(), []int{9}
}

func (x *AttributeWithCategory) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AttributeWithCategory) GetAttributeCategory() *AttributeCategoryWithoutAttributes {
	if x != nil {
		return x.AttributeCategory
	}
	return nil
}

var File_tmp_IIgYTah7KL protoreflect.FileDescriptor

const file_tmp_IIgYTah7KL_rawDesc = "" +
	"\n" +
	"\x0etmp.IIgYTah7KL\x12\x17ecommerce.attribute.get\"8\n" +
	"\x17ProductAttributeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\"\xaf\x01\n" +
	"\x18ProductAttributeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12N\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2..ecommerce.attribute.get.AttributeWithCategoryR\n" +
	"attributes\"M\n" +
	"\x1bAttributesCategoriesRequest\x12.\n" +
	"\x13product_category_id\x18\x01 \x03(\x05R\x11productCategoryId\"\xb1\x01\n" +
	"\x1cAttributesCategoriesResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12k\n" +
	"\x14attribute_categories\x18\x03 \x03(\v28.ecommerce.attribute.get.AttributeCategoryWithAttributesR\x13attributeCategories\"Z\n" +
	"$ProductsWithCertainAttributesRequest\x122\n" +
	"\x15product_attributes_id\x18\x01 \x03(\x05R\x13productAttributesId\"n\n" +
	"%ProductsWithCertainAttributesResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vproduct_ids\x18\x03 \x03(\x05R\n" +
	"productIds\"@\n" +
	"\x18AttributeWithoutCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"z\n" +
	"\"AttributeCategoryWithoutAttributes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12.\n" +
	"\x13product_category_id\x18\x02 \x01(\x05R\x11productCategoryId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"\xca\x01\n" +
	"\x1fAttributeCategoryWithAttributes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12.\n" +
	"\x13product_category_id\x18\x02 \x01(\x05R\x11productCategoryId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12Q\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v21.ecommerce.attribute.get.AttributeWithoutCategoryR\n" +
	"attributes\"\x99\x01\n" +
	"\x15AttributeWithCategory\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12j\n" +
	"\x12attribute_category\x18\x03 \x01(\v2;.ecommerce.attribute.get.AttributeCategoryWithoutAttributesR\x11attributeCategory2\xff\x05\n" +
	"\x10AttributeService\x12}\n" +
	"\x14GetProductAttributes\x120.ecommerce.attribute.get.ProductAttributeRequest\x1a1.ecommerce.attribute.get.ProductAttributeResponse\"\x00\x12\x88\x01\n" +
	"\x17GetAttributesCategories\x124.ecommerce.attribute.get.AttributesCategoriesRequest\x1a5.ecommerce.attribute.get.AttributesCategoriesResponse\"\x00\x12\xa3\x01\n" +
	" GetProductsWithCertainAttributes\x12=.ecommerce.attribute.get.ProductsWithCertainAttributesRequest\x1a>.ecommerce.attribute.get.ProductsWithCertainAttributesResponse\"\x00\x12\x8e\x01\n" +
	"\x1dGetSearchAttributesCategories\x124.ecommerce.attribute.get.AttributesCategoriesRequest\x1a5.ecommerce.attribute.get.AttributesCategoriesResponse\"\x00\x12\xa9\x01\n" +
	"&GetSearchProductsWithCertainAttributes\x12=.ecommerce.attribute.get.ProductsWithCertainAttributesRequest\x1a>.ecommerce.attribute.get.ProductsWithCertainAttributesResponse\"\x00B8Z6github.com/snappfood/attribute/ecommerce/attribute/getb\x06proto3"

var (
	file_tmp_IIgYTah7KL_rawDescOnce sync.Once
	file_tmp_IIgYTah7KL_rawDescData []byte
)

func file_tmp_IIgYTah7KL_rawDescGZIP() []byte {
	file_tmp_IIgYTah7KL_rawDescOnce.Do(func() {
		file_tmp_IIgYTah7KL_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tmp_IIgYTah7KL_rawDesc), len(file_tmp_IIgYTah7KL_rawDesc)))
	})
	return file_tmp_IIgYTah7KL_rawDescData
}

var file_tmp_IIgYTah7KL_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tmp_IIgYTah7KL_goTypes = []any{
	(*ProductAttributeRequest)(nil),               // 0: ecommerce.attribute.get.ProductAttributeRequest
	(*ProductAttributeResponse)(nil),              // 1: ecommerce.attribute.get.ProductAttributeResponse
	(*AttributesCategoriesRequest)(nil),           // 2: ecommerce.attribute.get.AttributesCategoriesRequest
	(*AttributesCategoriesResponse)(nil),          // 3: ecommerce.attribute.get.AttributesCategoriesResponse
	(*ProductsWithCertainAttributesRequest)(nil),  // 4: ecommerce.attribute.get.ProductsWithCertainAttributesRequest
	(*ProductsWithCertainAttributesResponse)(nil), // 5: ecommerce.attribute.get.ProductsWithCertainAttributesResponse
	(*AttributeWithoutCategory)(nil),              // 6: ecommerce.attribute.get.AttributeWithoutCategory
	(*AttributeCategoryWithoutAttributes)(nil),    // 7: ecommerce.attribute.get.AttributeCategoryWithoutAttributes
	(*AttributeCategoryWithAttributes)(nil),       // 8: ecommerce.attribute.get.AttributeCategoryWithAttributes
	(*AttributeWithCategory)(nil),                 // 9: ecommerce.attribute.get.AttributeWithCategory
}
var file_tmp_IIgYTah7KL_depIdxs = []int32{
	9, // 0: ecommerce.attribute.get.ProductAttributeResponse.attributes:type_name -> ecommerce.attribute.get.AttributeWithCategory
	8, // 1: ecommerce.attribute.get.AttributesCategoriesResponse.attribute_categories:type_name -> ecommerce.attribute.get.AttributeCategoryWithAttributes
	6, // 2: ecommerce.attribute.get.AttributeCategoryWithAttributes.attributes:type_name -> ecommerce.attribute.get.AttributeWithoutCategory
	7, // 3: ecommerce.attribute.get.AttributeWithCategory.attribute_category:type_name -> ecommerce.attribute.get.AttributeCategoryWithoutAttributes
	0, // 4: ecommerce.attribute.get.AttributeService.GetProductAttributes:input_type -> ecommerce.attribute.get.ProductAttributeRequest
	2, // 5: ecommerce.attribute.get.AttributeService.GetAttributesCategories:input_type -> ecommerce.attribute.get.AttributesCategoriesRequest
	4, // 6: ecommerce.attribute.get.AttributeService.GetProductsWithCertainAttributes:input_type -> ecommerce.attribute.get.ProductsWithCertainAttributesRequest
	2, // 7: ecommerce.attribute.get.AttributeService.GetSearchAttributesCategories:input_type -> ecommerce.attribute.get.AttributesCategoriesRequest
	4, // 8: ecommerce.attribute.get.AttributeService.GetSearchProductsWithCertainAttributes:input_type -> ecommerce.attribute.get.ProductsWithCertainAttributesRequest
	1, // 9: ecommerce.attribute.get.AttributeService.GetProductAttributes:output_type -> ecommerce.attribute.get.ProductAttributeResponse
	3, // 10: ecommerce.attribute.get.AttributeService.GetAttributesCategories:output_type -> ecommerce.attribute.get.AttributesCategoriesResponse
	5, // 11: ecommerce.attribute.get.AttributeService.GetProductsWithCertainAttributes:output_type -> ecommerce.attribute.get.ProductsWithCertainAttributesResponse
	3, // 12: ecommerce.attribute.get.AttributeService.GetSearchAttributesCategories:output_type -> ecommerce.attribute.get.AttributesCategoriesResponse
	5, // 13: ecommerce.attribute.get.AttributeService.GetSearchProductsWithCertainAttributes:output_type -> ecommerce.attribute.get.ProductsWithCertainAttributesResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tmp_IIgYTah7KL_init() }
func file_tmp_IIgYTah7KL_init() {
	if File_tmp_IIgYTah7KL != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tmp_IIgYTah7KL_rawDesc), len(file_tmp_IIgYTah7KL_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tmp_IIgYTah7KL_goTypes,
		DependencyIndexes: file_tmp_IIgYTah7KL_depIdxs,
		MessageInfos:      file_tmp_IIgYTah7KL_msgTypes,
	}.Build()
	File_tmp_IIgYTah7KL = out.File
	file_tmp_IIgYTah7KL_goTypes = nil
	file_tmp_IIgYTah7KL_depIdxs = nil
}
