version: "3.8"

services:
  redis:
    image: bitnami/redis:8.0.0
    container_name: redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=redis_password
    command: [ "redis-server", "--requirepass", "mI6G5jd3qNlJQinBOnA2z5SVEawLn4WV" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - appnet

  mongodb:
    image: bitnami/mongodb:8.0.9
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=mI6G5jd3qNlJQinBOnA2z5SVEawLn4WV
      - MONGODB_USERNAME=amirex128
      - MONGODB_PASSWORD=mI6G5jd3qNlJQinBOnA2z5SVEawLn4WV
      - MONGODB_DATABASE=new_site_builder
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_ENABLE_MAJORITY_READ=true
      - MONGODB_ENABLE_JOURNAL=true
      - MONGODB_INIT_RETRY_ATTEMPTS=7
      - MONGODB_INIT_RETRY_DELAY=5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb/data
      - ./mongodb/init-user.js:/docker-entrypoint-initdb.d/init-user.js:ro
    networks:
      - appnet

  vault:
    image: bitnami/vault:1.19.3
    container_name: vault
    restart: always
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
      - ./vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    command: server -config=/vault/config/vault.hcl
    user: root
    networks:
      - appnet

  mysql:
    image: bitnami/mysql:8.4.5
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mI6G5jd3qNlJQinBOnA2z5SVEawLn4WV
      - MYSQL_USER=amirex128
      - MYSQL_PASSWORD=mI6G5jd3qNlJQinBOnA2z5SVEawLn4WV
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/bitnami/mysql/data
      - ./mysql:/docker-entrypoint-startdb.d
    networks:
      - appnet

  minio:
    image: bitnami/minio:2025.4.22
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: amirex128
      MINIO_ROOT_PASSWORD: mI6G5jd3qNlJQinBOnA2z5SVEawLn4WV
      MINIO_USE_SSL: "false"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/bitnami/minio
    networks:
      - appnet

  openresty:
    image: bitnami/openresty:1.27.1-2
    container_name: openresty
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - openresty_conf:/opt/bitnami/openresty/conf
      - openresty_logs:/opt/bitnami/openresty/logs
      - openresty_html:/app  # Assuming you will serve app files here
    environment:
      - OPENRESTY_HTTP_PORT_NUMBER=8080
      - OPENRESTY_HTTPS_PORT_NUMBER=8443
    networks:
      - appnet

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  vault_data:
    driver: local
  mysql_data:
    driver: local
  minio_data:
    driver: local
  openresty_conf:
    driver: local
  openresty_logs:
    driver: local
  openresty_html:
    driver: local

networks:
  appnet:
    driver: bridge
