version: "3.8"

services:
  app:
    image: new-site-builder:latest
    container_name: new-site-builder
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    ports:
      - "8080:8080"
    networks:
      - appnet


networks:
  appnet:
    driver: bridge 