// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tmp.jzcYhL8Rvk

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shift int32

const (
	Shift_BREAKFAST    Shift = 0
	Shift_LUNCH        Shift = 1
	Shift_EVENING_MEAL Shift = 2
	Shift_DINNER       Shift = 3
	Shift_ALL          Shift = 4
)

// Enum value maps for Shift.
var (
	Shift_name = map[int32]string{
		0: "BREAKFAST",
		1: "LUNCH",
		2: "EVENING_MEAL",
		3: "DINNER",
		4: "ALL",
	}
	Shift_value = map[string]int32{
		"BREAKFAST":    0,
		"LUNCH":        1,
		"EVENING_MEAL": 2,
		"DINNER":       3,
		"ALL":          4,
	}
)

func (x Shift) Enum() *Shift {
	p := new(Shift)
	*p = x
	return p
}

func (x Shift) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Shift) Descriptor() protoreflect.EnumDescriptor {
	return file_tmp_jzcYhL8Rvk_enumTypes[0].Descriptor()
}

func (Shift) Type() protoreflect.EnumType {
	return &file_tmp_jzcYhL8Rvk_enumTypes[0]
}

func (x Shift) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Shift.Descriptor instead.
func (Shift) EnumDescriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{0}
}

type SuggestedRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserLatitude      float64                `protobuf:"fixed64,1,opt,name=UserLatitude,proto3" json:"UserLatitude,omitempty"`
	UserLongitude     float64                `protobuf:"fixed64,2,opt,name=UserLongitude,proto3" json:"UserLongitude,omitempty"`
	UserSessionID     string                 `protobuf:"bytes,3,opt,name=UserSessionID,proto3" json:"UserSessionID,omitempty"`
	Spots             []string               `protobuf:"bytes,10,rep,name=Spots,proto3" json:"Spots,omitempty"`
	VendorSuperTypeID uint64                 `protobuf:"varint,4,opt,name=VendorSuperTypeID,proto3" json:"VendorSuperTypeID,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SuggestedRequest) Reset() {
	*x = SuggestedRequest{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestedRequest) ProtoMessage() {}

func (x *SuggestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestedRequest.ProtoReflect.Descriptor instead.
func (*SuggestedRequest) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{0}
}

func (x *SuggestedRequest) GetUserLatitude() float64 {
	if x != nil {
		return x.UserLatitude
	}
	return 0
}

func (x *SuggestedRequest) GetUserLongitude() float64 {
	if x != nil {
		return x.UserLongitude
	}
	return 0
}

func (x *SuggestedRequest) GetUserSessionID() string {
	if x != nil {
		return x.UserSessionID
	}
	return ""
}

func (x *SuggestedRequest) GetSpots() []string {
	if x != nil {
		return x.Spots
	}
	return nil
}

func (x *SuggestedRequest) GetVendorSuperTypeID() uint64 {
	if x != nil {
		return x.VendorSuperTypeID
	}
	return 0
}

type SuggestedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []*SingleSpotResponse  `protobuf:"bytes,100,rep,name=Response,proto3" json:"Response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestedResponse) Reset() {
	*x = SuggestedResponse{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestedResponse) ProtoMessage() {}

func (x *SuggestedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestedResponse.ProtoReflect.Descriptor instead.
func (*SuggestedResponse) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{1}
}

func (x *SuggestedResponse) GetResponse() []*SingleSpotResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type SingleSpotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spot          string                 `protobuf:"bytes,1,opt,name=Spot,proto3" json:"Spot,omitempty"`
	Campaigns     []*SuggestedCampaigns  `protobuf:"bytes,100,rep,name=Campaigns,proto3" json:"Campaigns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleSpotResponse) Reset() {
	*x = SingleSpotResponse{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleSpotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleSpotResponse) ProtoMessage() {}

func (x *SingleSpotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleSpotResponse.ProtoReflect.Descriptor instead.
func (*SingleSpotResponse) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{2}
}

func (x *SingleSpotResponse) GetSpot() string {
	if x != nil {
		return x.Spot
	}
	return ""
}

func (x *SingleSpotResponse) GetCampaigns() []*SuggestedCampaigns {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

type SuggestedCampaigns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorID      uint32                 `protobuf:"varint,1,opt,name=VendorID,proto3" json:"VendorID,omitempty"`
	CampaignHash  string                 `protobuf:"bytes,10,opt,name=CampaignHash,proto3" json:"CampaignHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestedCampaigns) Reset() {
	*x = SuggestedCampaigns{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestedCampaigns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestedCampaigns) ProtoMessage() {}

func (x *SuggestedCampaigns) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestedCampaigns.ProtoReflect.Descriptor instead.
func (*SuggestedCampaigns) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{3}
}

func (x *SuggestedCampaigns) GetVendorID() uint32 {
	if x != nil {
		return x.VendorID
	}
	return 0
}

func (x *SuggestedCampaigns) GetCampaignHash() string {
	if x != nil {
		return x.CampaignHash
	}
	return ""
}

// Packages
type GetPackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,10,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	SuperType     int64                  `protobuf:"varint,20,opt,name=SuperType,proto3" json:"SuperType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackagesRequest) Reset() {
	*x = GetPackagesRequest{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackagesRequest) ProtoMessage() {}

func (x *GetPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackagesRequest.ProtoReflect.Descriptor instead.
func (*GetPackagesRequest) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{4}
}

func (x *GetPackagesRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetPackagesRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetPackagesRequest) GetSuperType() int64 {
	if x != nil {
		return x.SuperType
	}
	return 0
}

type GetPackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Packages      []*Package             `protobuf:"bytes,100,rep,name=Packages,proto3" json:"Packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackagesResponse) Reset() {
	*x = GetPackagesResponse{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackagesResponse) ProtoMessage() {}

func (x *GetPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackagesResponse.ProtoReflect.Descriptor instead.
func (*GetPackagesResponse) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{5}
}

func (x *GetPackagesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPackagesResponse) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=Price,proto3" json:"Price,omitempty"`
	VendorID      int64                  `protobuf:"varint,5,opt,name=VendorID,proto3" json:"VendorID,omitempty"`
	PackageID     string                 `protobuf:"bytes,30,opt,name=PackageID,proto3" json:"PackageID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{6}
}

func (x *Package) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Package) GetVendorID() int64 {
	if x != nil {
		return x.VendorID
	}
	return 0
}

func (x *Package) GetPackageID() string {
	if x != nil {
		return x.PackageID
	}
	return ""
}

type VendorSuperType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=Alias,proto3" json:"Alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorSuperType) Reset() {
	*x = VendorSuperType{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorSuperType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorSuperType) ProtoMessage() {}

func (x *VendorSuperType) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorSuperType.ProtoReflect.Descriptor instead.
func (*VendorSuperType) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{7}
}

func (x *VendorSuperType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VendorSuperType) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type Area struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,10,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,20,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	IsActivated   bool                   `protobuf:"varint,30,opt,name=IsActivated,proto3" json:"IsActivated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Area) Reset() {
	*x = Area{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Area) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Area) ProtoMessage() {}

func (x *Area) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Area.ProtoReflect.Descriptor instead.
func (*Area) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{8}
}

func (x *Area) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Area) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Area) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Area) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Area) GetIsActivated() bool {
	if x != nil {
		return x.IsActivated
	}
	return false
}

type SetImpressionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserSessionID     string                 `protobuf:"bytes,1,opt,name=UserSessionID,proto3" json:"UserSessionID,omitempty"`
	SpotCampaignsList []*SpotCampaigns       `protobuf:"bytes,20,rep,name=SpotCampaignsList,proto3" json:"SpotCampaignsList,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetImpressionRequest) Reset() {
	*x = SetImpressionRequest{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetImpressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetImpressionRequest) ProtoMessage() {}

func (x *SetImpressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetImpressionRequest.ProtoReflect.Descriptor instead.
func (*SetImpressionRequest) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{9}
}

func (x *SetImpressionRequest) GetUserSessionID() string {
	if x != nil {
		return x.UserSessionID
	}
	return ""
}

func (x *SetImpressionRequest) GetSpotCampaignsList() []*SpotCampaigns {
	if x != nil {
		return x.SpotCampaignsList
	}
	return nil
}

type SpotCampaigns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spot          string                 `protobuf:"bytes,1,opt,name=Spot,proto3" json:"Spot,omitempty"`
	PackageHash   string                 `protobuf:"bytes,10,opt,name=PackageHash,proto3" json:"PackageHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpotCampaigns) Reset() {
	*x = SpotCampaigns{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotCampaigns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotCampaigns) ProtoMessage() {}

func (x *SpotCampaigns) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotCampaigns.ProtoReflect.Descriptor instead.
func (*SpotCampaigns) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{10}
}

func (x *SpotCampaigns) GetSpot() string {
	if x != nil {
		return x.Spot
	}
	return ""
}

func (x *SpotCampaigns) GetPackageHash() string {
	if x != nil {
		return x.PackageHash
	}
	return ""
}

type SetImpressionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetImpressionResponse) Reset() {
	*x = SetImpressionResponse{}
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetImpressionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetImpressionResponse) ProtoMessage() {}

func (x *SetImpressionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_jzcYhL8Rvk_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetImpressionResponse.ProtoReflect.Descriptor instead.
func (*SetImpressionResponse) Descriptor() ([]byte, []int) {
	return file_tmp_jzcYhL8Rvk_rawDescGZIP(), []int{11}
}

var File_tmp_jzcYhL8Rvk protoreflect.FileDescriptor

const file_tmp_jzcYhL8Rvk_rawDesc = "" +
	"\n" +
	"\x0etmp.jzcYhL8Rvk\x12\aservice\"\xc6\x01\n" +
	"\x10SuggestedRequest\x12\"\n" +
	"\fUserLatitude\x18\x01 \x01(\x01R\fUserLatitude\x12$\n" +
	"\rUserLongitude\x18\x02 \x01(\x01R\rUserLongitude\x12$\n" +
	"\rUserSessionID\x18\x03 \x01(\tR\rUserSessionID\x12\x14\n" +
	"\x05Spots\x18\n" +
	" \x03(\tR\x05Spots\x12,\n" +
	"\x11VendorSuperTypeID\x18\x04 \x01(\x04R\x11VendorSuperTypeID\"L\n" +
	"\x11SuggestedResponse\x127\n" +
	"\bResponse\x18d \x03(\v2\x1b.service.SingleSpotResponseR\bResponse\"c\n" +
	"\x12SingleSpotResponse\x12\x12\n" +
	"\x04Spot\x18\x01 \x01(\tR\x04Spot\x129\n" +
	"\tCampaigns\x18d \x03(\v2\x1b.service.SuggestedCampaignsR\tCampaigns\"T\n" +
	"\x12SuggestedCampaigns\x12\x1a\n" +
	"\bVendorID\x18\x01 \x01(\rR\bVendorID\x12\"\n" +
	"\fCampaignHash\x18\n" +
	" \x01(\tR\fCampaignHash\"l\n" +
	"\x12GetPackagesRequest\x12\x1a\n" +
	"\bLatitude\x18\x01 \x01(\x01R\bLatitude\x12\x1c\n" +
	"\tLongitude\x18\n" +
	" \x01(\x01R\tLongitude\x12\x1c\n" +
	"\tSuperType\x18\x14 \x01(\x03R\tSuperType\"[\n" +
	"\x13GetPackagesResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\x12,\n" +
	"\bPackages\x18d \x03(\v2\x10.service.PackageR\bPackages\"Y\n" +
	"\aPackage\x12\x14\n" +
	"\x05Price\x18\x01 \x01(\x01R\x05Price\x12\x1a\n" +
	"\bVendorID\x18\x05 \x01(\x03R\bVendorID\x12\x1c\n" +
	"\tPackageID\x18\x1e \x01(\tR\tPackageID\";\n" +
	"\x0fVendorSuperType\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Alias\x18\x02 \x01(\tR\x05Alias\"\x86\x01\n" +
	"\x04Area\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bLatitude\x18\n" +
	" \x01(\x01R\bLatitude\x12\x1c\n" +
	"\tLongitude\x18\x14 \x01(\x01R\tLongitude\x12 \n" +
	"\vIsActivated\x18\x1e \x01(\bR\vIsActivated\"\x82\x01\n" +
	"\x14SetImpressionRequest\x12$\n" +
	"\rUserSessionID\x18\x01 \x01(\tR\rUserSessionID\x12D\n" +
	"\x11SpotCampaignsList\x18\x14 \x03(\v2\x16.service.SpotCampaignsR\x11SpotCampaignsList\"E\n" +
	"\rSpotCampaigns\x12\x12\n" +
	"\x04Spot\x18\x01 \x01(\tR\x04Spot\x12 \n" +
	"\vPackageHash\x18\n" +
	" \x01(\tR\vPackageHash\"\x17\n" +
	"\x15SetImpressionResponse*H\n" +
	"\x05Shift\x12\r\n" +
	"\tBREAKFAST\x10\x00\x12\t\n" +
	"\x05LUNCH\x10\x01\x12\x10\n" +
	"\fEVENING_MEAL\x10\x02\x12\n" +
	"\n" +
	"\x06DINNER\x10\x03\x12\a\n" +
	"\x03ALL\x10\x042\xe7\x01\n" +
	"\aService\x12B\n" +
	"\tSuggested\x12\x19.service.SuggestedRequest\x1a\x1a.service.SuggestedResponse\x12H\n" +
	"\vGetPackages\x12\x1b.service.GetPackagesRequest\x1a\x1c.service.GetPackagesResponse\x12N\n" +
	"\rSetImpression\x12\x1d.service.SetImpressionRequest\x1a\x1e.service.SetImpressionResponseB\vZ\t./serviceb\x06proto3"

var (
	file_tmp_jzcYhL8Rvk_rawDescOnce sync.Once
	file_tmp_jzcYhL8Rvk_rawDescData []byte
)

func file_tmp_jzcYhL8Rvk_rawDescGZIP() []byte {
	file_tmp_jzcYhL8Rvk_rawDescOnce.Do(func() {
		file_tmp_jzcYhL8Rvk_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tmp_jzcYhL8Rvk_rawDesc), len(file_tmp_jzcYhL8Rvk_rawDesc)))
	})
	return file_tmp_jzcYhL8Rvk_rawDescData
}

var file_tmp_jzcYhL8Rvk_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tmp_jzcYhL8Rvk_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tmp_jzcYhL8Rvk_goTypes = []any{
	(Shift)(0),                    // 0: service.Shift
	(*SuggestedRequest)(nil),      // 1: service.SuggestedRequest
	(*SuggestedResponse)(nil),     // 2: service.SuggestedResponse
	(*SingleSpotResponse)(nil),    // 3: service.SingleSpotResponse
	(*SuggestedCampaigns)(nil),    // 4: service.SuggestedCampaigns
	(*GetPackagesRequest)(nil),    // 5: service.GetPackagesRequest
	(*GetPackagesResponse)(nil),   // 6: service.GetPackagesResponse
	(*Package)(nil),               // 7: service.Package
	(*VendorSuperType)(nil),       // 8: service.VendorSuperType
	(*Area)(nil),                  // 9: service.Area
	(*SetImpressionRequest)(nil),  // 10: service.SetImpressionRequest
	(*SpotCampaigns)(nil),         // 11: service.SpotCampaigns
	(*SetImpressionResponse)(nil), // 12: service.SetImpressionResponse
}
var file_tmp_jzcYhL8Rvk_depIdxs = []int32{
	3,  // 0: service.SuggestedResponse.Response:type_name -> service.SingleSpotResponse
	4,  // 1: service.SingleSpotResponse.Campaigns:type_name -> service.SuggestedCampaigns
	7,  // 2: service.GetPackagesResponse.Packages:type_name -> service.Package
	11, // 3: service.SetImpressionRequest.SpotCampaignsList:type_name -> service.SpotCampaigns
	1,  // 4: service.Service.Suggested:input_type -> service.SuggestedRequest
	5,  // 5: service.Service.GetPackages:input_type -> service.GetPackagesRequest
	10, // 6: service.Service.SetImpression:input_type -> service.SetImpressionRequest
	2,  // 7: service.Service.Suggested:output_type -> service.SuggestedResponse
	6,  // 8: service.Service.GetPackages:output_type -> service.GetPackagesResponse
	12, // 9: service.Service.SetImpression:output_type -> service.SetImpressionResponse
	7,  // [7:10] is the sub-list for method output_type
	4,  // [4:7] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_tmp_jzcYhL8Rvk_init() }
func file_tmp_jzcYhL8Rvk_init() {
	if File_tmp_jzcYhL8Rvk != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tmp_jzcYhL8Rvk_rawDesc), len(file_tmp_jzcYhL8Rvk_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tmp_jzcYhL8Rvk_goTypes,
		DependencyIndexes: file_tmp_jzcYhL8Rvk_depIdxs,
		EnumInfos:         file_tmp_jzcYhL8Rvk_enumTypes,
		MessageInfos:      file_tmp_jzcYhL8Rvk_msgTypes,
	}.Build()
	File_tmp_jzcYhL8Rvk = out.File
	file_tmp_jzcYhL8Rvk_goTypes = nil
	file_tmp_jzcYhL8Rvk_depIdxs = nil
}
