// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tmp.DruE8rlWKP

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vendor struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsExpress         bool                   `protobuf:"varint,2,opt,name=is_express,json=isExpress,proto3" json:"is_express,omitempty"`
	DeliveryFee       int64                  `protobuf:"varint,3,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	DoesDeliver       bool                   `protobuf:"varint,4,opt,name=does_deliver,json=doesDeliver,proto3" json:"does_deliver,omitempty"`
	Detail            *DeliveryDetail        `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	MinimumOrderValue int64                  `protobuf:"varint,6,opt,name=minimum_order_value,json=minimumOrderValue,proto3" json:"minimum_order_value,omitempty"`
	DeliveryStatus    string                 `protobuf:"bytes,7,opt,name=delivery_status,json=deliveryStatus,proto3" json:"delivery_status,omitempty"`
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Vendor) Reset() {
	*x = Vendor{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendor) ProtoMessage() {}

func (x *Vendor) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendor.ProtoReflect.Descriptor instead.
func (*Vendor) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{0}
}

func (x *Vendor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vendor) GetIsExpress() bool {
	if x != nil {
		return x.IsExpress
	}
	return false
}

func (x *Vendor) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *Vendor) GetDoesDeliver() bool {
	if x != nil {
		return x.DoesDeliver
	}
	return false
}

func (x *Vendor) GetDetail() *DeliveryDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Vendor) GetMinimumOrderValue() int64 {
	if x != nil {
		return x.MinimumOrderValue
	}
	return 0
}

func (x *Vendor) GetDeliveryStatus() string {
	if x != nil {
		return x.DeliveryStatus
	}
	return ""
}

func (x *Vendor) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderPickUpVendor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DoesDeliver   bool                   `protobuf:"varint,2,opt,name=does_deliver,json=doesDeliver,proto3" json:"does_deliver,omitempty"`
	DeliveryFee   int64                  `protobuf:"varint,3,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	Details       *OrderPickupDetail     `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPickUpVendor) Reset() {
	*x = OrderPickUpVendor{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPickUpVendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPickUpVendor) ProtoMessage() {}

func (x *OrderPickUpVendor) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPickUpVendor.ProtoReflect.Descriptor instead.
func (*OrderPickUpVendor) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{1}
}

func (x *OrderPickUpVendor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderPickUpVendor) GetDoesDeliver() bool {
	if x != nil {
		return x.DoesDeliver
	}
	return false
}

func (x *OrderPickUpVendor) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *OrderPickUpVendor) GetDetails() *OrderPickupDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

type DeliveryDetail struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	VendorId                 int64                  `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	NormalPreparationTime    int64                  `protobuf:"varint,2,opt,name=normal_preparation_time,json=normalPreparationTime,proto3" json:"normal_preparation_time,omitempty"`
	NormalTimeFactor         int64                  `protobuf:"varint,3,opt,name=normal_time_factor,json=normalTimeFactor,proto3" json:"normal_time_factor,omitempty"`
	SafetyTimeFactor         int64                  `protobuf:"varint,4,opt,name=safety_time_factor,json=safetyTimeFactor,proto3" json:"safety_time_factor,omitempty"`
	DriveTime                int64                  `protobuf:"varint,5,opt,name=drive_time,json=driveTime,proto3" json:"drive_time,omitempty"`
	MinThresholdDeliveryTime int64                  `protobuf:"varint,6,opt,name=min_threshold_delivery_time,json=minThresholdDeliveryTime,proto3" json:"min_threshold_delivery_time,omitempty"`
	MaxThresholdDeliveryTime int64                  `protobuf:"varint,7,opt,name=max_threshold_delivery_time,json=maxThresholdDeliveryTime,proto3" json:"max_threshold_delivery_time,omitempty"`
	TotalTime                int64                  `protobuf:"varint,8,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	DelayTime                int64                  `protobuf:"varint,9,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`
	OpenAtEta                bool                   `protobuf:"varint,10,opt,name=open_at_eta,json=openAtEta,proto3" json:"open_at_eta,omitempty"`
	Action                   string                 `protobuf:"bytes,11,opt,name=action,proto3" json:"action,omitempty"`
	MaxTotalTime             int64                  `protobuf:"varint,12,opt,name=max_total_time,json=maxTotalTime,proto3" json:"max_total_time,omitempty"`
	MinTotalTime             int64                  `protobuf:"varint,13,opt,name=min_total_time,json=minTotalTime,proto3" json:"min_total_time,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DeliveryDetail) Reset() {
	*x = DeliveryDetail{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryDetail) ProtoMessage() {}

func (x *DeliveryDetail) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryDetail.ProtoReflect.Descriptor instead.
func (*DeliveryDetail) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{2}
}

func (x *DeliveryDetail) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *DeliveryDetail) GetNormalPreparationTime() int64 {
	if x != nil {
		return x.NormalPreparationTime
	}
	return 0
}

func (x *DeliveryDetail) GetNormalTimeFactor() int64 {
	if x != nil {
		return x.NormalTimeFactor
	}
	return 0
}

func (x *DeliveryDetail) GetSafetyTimeFactor() int64 {
	if x != nil {
		return x.SafetyTimeFactor
	}
	return 0
}

func (x *DeliveryDetail) GetDriveTime() int64 {
	if x != nil {
		return x.DriveTime
	}
	return 0
}

func (x *DeliveryDetail) GetMinThresholdDeliveryTime() int64 {
	if x != nil {
		return x.MinThresholdDeliveryTime
	}
	return 0
}

func (x *DeliveryDetail) GetMaxThresholdDeliveryTime() int64 {
	if x != nil {
		return x.MaxThresholdDeliveryTime
	}
	return 0
}

func (x *DeliveryDetail) GetTotalTime() int64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *DeliveryDetail) GetDelayTime() int64 {
	if x != nil {
		return x.DelayTime
	}
	return 0
}

func (x *DeliveryDetail) GetOpenAtEta() bool {
	if x != nil {
		return x.OpenAtEta
	}
	return false
}

func (x *DeliveryDetail) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DeliveryDetail) GetMaxTotalTime() int64 {
	if x != nil {
		return x.MaxTotalTime
	}
	return 0
}

func (x *DeliveryDetail) GetMinTotalTime() int64 {
	if x != nil {
		return x.MinTotalTime
	}
	return 0
}

type OrderPickupDetail struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	VendorId              int64                  `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	NormalPreparationTime int64                  `protobuf:"varint,2,opt,name=normal_preparation_time,json=normalPreparationTime,proto3" json:"normal_preparation_time,omitempty"`
	TotalTime             int64                  `protobuf:"varint,8,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OrderPickupDetail) Reset() {
	*x = OrderPickupDetail{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPickupDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPickupDetail) ProtoMessage() {}

func (x *OrderPickupDetail) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPickupDetail.ProtoReflect.Descriptor instead.
func (*OrderPickupDetail) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{3}
}

func (x *OrderPickupDetail) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *OrderPickupDetail) GetNormalPreparationTime() int64 {
	if x != nil {
		return x.NormalPreparationTime
	}
	return 0
}

func (x *OrderPickupDetail) GetTotalTime() int64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

type GetAllVendorsQuery struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Longitude             float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude              float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	GetOrderPickupVendors bool                   `protobuf:"varint,3,opt,name=get_order_pickup_vendors,json=getOrderPickupVendors,proto3" json:"get_order_pickup_vendors,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetAllVendorsQuery) Reset() {
	*x = GetAllVendorsQuery{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllVendorsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVendorsQuery) ProtoMessage() {}

func (x *GetAllVendorsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVendorsQuery.ProtoReflect.Descriptor instead.
func (*GetAllVendorsQuery) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{4}
}

func (x *GetAllVendorsQuery) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetAllVendorsQuery) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetAllVendorsQuery) GetGetOrderPickupVendors() bool {
	if x != nil {
		return x.GetOrderPickupVendors
	}
	return false
}

type GetAllVendorsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Vendors            []*Vendor              `protobuf:"bytes,1,rep,name=vendors,proto3" json:"vendors,omitempty"`
	OrderPickupVendors []*OrderPickUpVendor   `protobuf:"bytes,2,rep,name=order_pickup_vendors,json=orderPickupVendors,proto3" json:"order_pickup_vendors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAllVendorsResponse) Reset() {
	*x = GetAllVendorsResponse{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllVendorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVendorsResponse) ProtoMessage() {}

func (x *GetAllVendorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVendorsResponse.ProtoReflect.Descriptor instead.
func (*GetAllVendorsResponse) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{5}
}

func (x *GetAllVendorsResponse) GetVendors() []*Vendor {
	if x != nil {
		return x.Vendors
	}
	return nil
}

func (x *GetAllVendorsResponse) GetOrderPickupVendors() []*OrderPickUpVendor {
	if x != nil {
		return x.OrderPickupVendors
	}
	return nil
}

type GetVendorsByIdsQuery struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Longitude              float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude               float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	VendorIds              []int64                `protobuf:"varint,3,rep,packed,name=vendor_ids,json=vendorIds,proto3" json:"vendor_ids,omitempty"`
	DontProcessDetail      bool                   `protobuf:"varint,4,opt,name=dont_process_detail,json=dontProcessDetail,proto3" json:"dont_process_detail,omitempty"`
	Time                   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	GetOrderPickupVendors  bool                   `protobuf:"varint,6,opt,name=get_order_pickup_vendors,json=getOrderPickupVendors,proto3" json:"get_order_pickup_vendors,omitempty"`
	DontProcessExpectation bool                   `protobuf:"varint,7,opt,name=dont_process_expectation,json=dontProcessExpectation,proto3" json:"dont_process_expectation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetVendorsByIdsQuery) Reset() {
	*x = GetVendorsByIdsQuery{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendorsByIdsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendorsByIdsQuery) ProtoMessage() {}

func (x *GetVendorsByIdsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendorsByIdsQuery.ProtoReflect.Descriptor instead.
func (*GetVendorsByIdsQuery) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{6}
}

func (x *GetVendorsByIdsQuery) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetVendorsByIdsQuery) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetVendorsByIdsQuery) GetVendorIds() []int64 {
	if x != nil {
		return x.VendorIds
	}
	return nil
}

func (x *GetVendorsByIdsQuery) GetDontProcessDetail() bool {
	if x != nil {
		return x.DontProcessDetail
	}
	return false
}

func (x *GetVendorsByIdsQuery) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GetVendorsByIdsQuery) GetGetOrderPickupVendors() bool {
	if x != nil {
		return x.GetOrderPickupVendors
	}
	return false
}

func (x *GetVendorsByIdsQuery) GetDontProcessExpectation() bool {
	if x != nil {
		return x.DontProcessExpectation
	}
	return false
}

type GetVendorsByIdsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Vendors            []*Vendor              `protobuf:"bytes,1,rep,name=vendors,proto3" json:"vendors,omitempty"`
	OrderPickupVendors []*OrderPickUpVendor   `protobuf:"bytes,2,rep,name=order_pickup_vendors,json=orderPickupVendors,proto3" json:"order_pickup_vendors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetVendorsByIdsResponse) Reset() {
	*x = GetVendorsByIdsResponse{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendorsByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendorsByIdsResponse) ProtoMessage() {}

func (x *GetVendorsByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendorsByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetVendorsByIdsResponse) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{7}
}

func (x *GetVendorsByIdsResponse) GetVendors() []*Vendor {
	if x != nil {
		return x.Vendors
	}
	return nil
}

func (x *GetVendorsByIdsResponse) GetOrderPickupVendors() []*OrderPickUpVendor {
	if x != nil {
		return x.OrderPickupVendors
	}
	return nil
}

type GetDeliveryEstimationTimeByOrderQuery struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Longitude              float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude               float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	OrderId                int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	VendorId               int64                  `protobuf:"varint,4,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	VendorType             string                 `protobuf:"bytes,5,opt,name=vendor_type,json=vendorType,proto3" json:"vendor_type,omitempty"`
	DontProcessExpectation bool                   `protobuf:"varint,6,opt,name=dont_process_expectation,json=dontProcessExpectation,proto3" json:"dont_process_expectation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetDeliveryEstimationTimeByOrderQuery) Reset() {
	*x = GetDeliveryEstimationTimeByOrderQuery{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryEstimationTimeByOrderQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryEstimationTimeByOrderQuery) ProtoMessage() {}

func (x *GetDeliveryEstimationTimeByOrderQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryEstimationTimeByOrderQuery.ProtoReflect.Descriptor instead.
func (*GetDeliveryEstimationTimeByOrderQuery) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{8}
}

func (x *GetDeliveryEstimationTimeByOrderQuery) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderQuery) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderQuery) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderQuery) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderQuery) GetVendorType() string {
	if x != nil {
		return x.VendorType
	}
	return ""
}

func (x *GetDeliveryEstimationTimeByOrderQuery) GetDontProcessExpectation() bool {
	if x != nil {
		return x.DontProcessExpectation
	}
	return false
}

type GetDeliveryEstimationTimeByOrderResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	VendorId              int64                  `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	NormalPreparationTime int64                  `protobuf:"varint,2,opt,name=normal_preparation_time,json=normalPreparationTime,proto3" json:"normal_preparation_time,omitempty"`
	NormalTimeFactor      int64                  `protobuf:"varint,3,opt,name=normal_time_factor,json=normalTimeFactor,proto3" json:"normal_time_factor,omitempty"`
	SafetyTimeFactor      int64                  `protobuf:"varint,4,opt,name=safety_time_factor,json=safetyTimeFactor,proto3" json:"safety_time_factor,omitempty"`
	BikerFound            int64                  `protobuf:"varint,5,opt,name=biker_found,json=bikerFound,proto3" json:"biker_found,omitempty"`
	OrdersAround          int64                  `protobuf:"varint,6,opt,name=orders_around,json=ordersAround,proto3" json:"orders_around,omitempty"`
	DriveTime             int64                  `protobuf:"varint,7,opt,name=drive_time,json=driveTime,proto3" json:"drive_time,omitempty"`
	AvailabilityIndex     float32                `protobuf:"fixed32,8,opt,name=availability_index,json=availabilityIndex,proto3" json:"availability_index,omitempty"`
	TotalTime             int64                  `protobuf:"varint,9,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	BasketCoefficient     float32                `protobuf:"fixed32,10,opt,name=basket_coefficient,json=basketCoefficient,proto3" json:"basket_coefficient,omitempty"`
	BasketSize            float32                `protobuf:"fixed32,11,opt,name=basket_size,json=basketSize,proto3" json:"basket_size,omitempty"`
	DelayTime             int64                  `protobuf:"varint,12,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetDeliveryEstimationTimeByOrderResponse) Reset() {
	*x = GetDeliveryEstimationTimeByOrderResponse{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryEstimationTimeByOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryEstimationTimeByOrderResponse) ProtoMessage() {}

func (x *GetDeliveryEstimationTimeByOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryEstimationTimeByOrderResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryEstimationTimeByOrderResponse) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{9}
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetNormalPreparationTime() int64 {
	if x != nil {
		return x.NormalPreparationTime
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetNormalTimeFactor() int64 {
	if x != nil {
		return x.NormalTimeFactor
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetSafetyTimeFactor() int64 {
	if x != nil {
		return x.SafetyTimeFactor
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetBikerFound() int64 {
	if x != nil {
		return x.BikerFound
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetOrdersAround() int64 {
	if x != nil {
		return x.OrdersAround
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetDriveTime() int64 {
	if x != nil {
		return x.DriveTime
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetAvailabilityIndex() float32 {
	if x != nil {
		return x.AvailabilityIndex
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetTotalTime() int64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetBasketCoefficient() float32 {
	if x != nil {
		return x.BasketCoefficient
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetBasketSize() float32 {
	if x != nil {
		return x.BasketSize
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByOrderResponse) GetDelayTime() int64 {
	if x != nil {
		return x.DelayTime
	}
	return 0
}

type GetDeliveryEstimationTimeByBasketQuery struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Longitude              float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude               float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	VendorId               int64                  `protobuf:"varint,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	VendorType             string                 `protobuf:"bytes,4,opt,name=vendor_type,json=vendorType,proto3" json:"vendor_type,omitempty"`
	ProductVariationIds    []int64                `protobuf:"varint,5,rep,packed,name=product_variation_ids,json=productVariationIds,proto3" json:"product_variation_ids,omitempty"`
	DontProcessExpectation bool                   `protobuf:"varint,6,opt,name=dont_process_expectation,json=dontProcessExpectation,proto3" json:"dont_process_expectation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetDeliveryEstimationTimeByBasketQuery) Reset() {
	*x = GetDeliveryEstimationTimeByBasketQuery{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryEstimationTimeByBasketQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryEstimationTimeByBasketQuery) ProtoMessage() {}

func (x *GetDeliveryEstimationTimeByBasketQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryEstimationTimeByBasketQuery.ProtoReflect.Descriptor instead.
func (*GetDeliveryEstimationTimeByBasketQuery) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{10}
}

func (x *GetDeliveryEstimationTimeByBasketQuery) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketQuery) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketQuery) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketQuery) GetVendorType() string {
	if x != nil {
		return x.VendorType
	}
	return ""
}

func (x *GetDeliveryEstimationTimeByBasketQuery) GetProductVariationIds() []int64 {
	if x != nil {
		return x.ProductVariationIds
	}
	return nil
}

func (x *GetDeliveryEstimationTimeByBasketQuery) GetDontProcessExpectation() bool {
	if x != nil {
		return x.DontProcessExpectation
	}
	return false
}

type GetDeliveryEstimationTimeByBasketResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	VendorId              int64                  `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	NormalPreparationTime int64                  `protobuf:"varint,2,opt,name=normal_preparation_time,json=normalPreparationTime,proto3" json:"normal_preparation_time,omitempty"`
	NormalTimeFactor      int64                  `protobuf:"varint,3,opt,name=normal_time_factor,json=normalTimeFactor,proto3" json:"normal_time_factor,omitempty"`
	SafetyTimeFactor      int64                  `protobuf:"varint,4,opt,name=safety_time_factor,json=safetyTimeFactor,proto3" json:"safety_time_factor,omitempty"`
	BikerFound            int64                  `protobuf:"varint,5,opt,name=biker_found,json=bikerFound,proto3" json:"biker_found,omitempty"`
	OrdersAround          int64                  `protobuf:"varint,6,opt,name=orders_around,json=ordersAround,proto3" json:"orders_around,omitempty"`
	DriveTime             int64                  `protobuf:"varint,7,opt,name=drive_time,json=driveTime,proto3" json:"drive_time,omitempty"`
	AvailabilityIndex     float32                `protobuf:"fixed32,8,opt,name=availability_index,json=availabilityIndex,proto3" json:"availability_index,omitempty"`
	TotalTime             int64                  `protobuf:"varint,9,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	BasketCoefficient     float32                `protobuf:"fixed32,10,opt,name=basket_coefficient,json=basketCoefficient,proto3" json:"basket_coefficient,omitempty"`
	BasketSize            float32                `protobuf:"fixed32,11,opt,name=basket_size,json=basketSize,proto3" json:"basket_size,omitempty"`
	DelayTime             int64                  `protobuf:"varint,12,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetDeliveryEstimationTimeByBasketResponse) Reset() {
	*x = GetDeliveryEstimationTimeByBasketResponse{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryEstimationTimeByBasketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryEstimationTimeByBasketResponse) ProtoMessage() {}

func (x *GetDeliveryEstimationTimeByBasketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryEstimationTimeByBasketResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryEstimationTimeByBasketResponse) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{11}
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetNormalPreparationTime() int64 {
	if x != nil {
		return x.NormalPreparationTime
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetNormalTimeFactor() int64 {
	if x != nil {
		return x.NormalTimeFactor
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetSafetyTimeFactor() int64 {
	if x != nil {
		return x.SafetyTimeFactor
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetBikerFound() int64 {
	if x != nil {
		return x.BikerFound
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetOrdersAround() int64 {
	if x != nil {
		return x.OrdersAround
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetDriveTime() int64 {
	if x != nil {
		return x.DriveTime
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetAvailabilityIndex() float32 {
	if x != nil {
		return x.AvailabilityIndex
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetTotalTime() int64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetBasketCoefficient() float32 {
	if x != nil {
		return x.BasketCoefficient
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetBasketSize() float32 {
	if x != nil {
		return x.BasketSize
	}
	return 0
}

func (x *GetDeliveryEstimationTimeByBasketResponse) GetDelayTime() int64 {
	if x != nil {
		return x.DelayTime
	}
	return 0
}

type GetOrderPickupVendorsQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderPickupVendorsQuery) Reset() {
	*x = GetOrderPickupVendorsQuery{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderPickupVendorsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderPickupVendorsQuery) ProtoMessage() {}

func (x *GetOrderPickupVendorsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderPickupVendorsQuery.ProtoReflect.Descriptor instead.
func (*GetOrderPickupVendorsQuery) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{12}
}

func (x *GetOrderPickupVendorsQuery) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetOrderPickupVendorsQuery) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type GetOrderPickupVendorsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderPickupVendors []*OrderPickUpVendor   `protobuf:"bytes,1,rep,name=order_pickup_vendors,json=orderPickupVendors,proto3" json:"order_pickup_vendors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetOrderPickupVendorsResponse) Reset() {
	*x = GetOrderPickupVendorsResponse{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderPickupVendorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderPickupVendorsResponse) ProtoMessage() {}

func (x *GetOrderPickupVendorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderPickupVendorsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderPickupVendorsResponse) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{13}
}

func (x *GetOrderPickupVendorsResponse) GetOrderPickupVendors() []*OrderPickUpVendor {
	if x != nil {
		return x.OrderPickupVendors
	}
	return nil
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{14}
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type GetVendorByMultipleCoordinatesQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   []*Coordinate          `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	VendorId      int64                  `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVendorByMultipleCoordinatesQuery) Reset() {
	*x = GetVendorByMultipleCoordinatesQuery{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendorByMultipleCoordinatesQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendorByMultipleCoordinatesQuery) ProtoMessage() {}

func (x *GetVendorByMultipleCoordinatesQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendorByMultipleCoordinatesQuery.ProtoReflect.Descriptor instead.
func (*GetVendorByMultipleCoordinatesQuery) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{15}
}

func (x *GetVendorByMultipleCoordinatesQuery) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *GetVendorByMultipleCoordinatesQuery) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *GetVendorByMultipleCoordinatesQuery) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type SimpleVendor struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DoesDeliver            bool                   `protobuf:"varint,2,opt,name=does_deliver,json=doesDeliver,proto3" json:"does_deliver,omitempty"`
	DeliveryFee            int64                  `protobuf:"varint,3,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	DoesSupportOrderPickup bool                   `protobuf:"varint,4,opt,name=does_support_order_pickup,json=doesSupportOrderPickup,proto3" json:"does_support_order_pickup,omitempty"`
	IsExpress              bool                   `protobuf:"varint,5,opt,name=is_express,json=isExpress,proto3" json:"is_express,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SimpleVendor) Reset() {
	*x = SimpleVendor{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleVendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleVendor) ProtoMessage() {}

func (x *SimpleVendor) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleVendor.ProtoReflect.Descriptor instead.
func (*SimpleVendor) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{16}
}

func (x *SimpleVendor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SimpleVendor) GetDoesDeliver() bool {
	if x != nil {
		return x.DoesDeliver
	}
	return false
}

func (x *SimpleVendor) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *SimpleVendor) GetDoesSupportOrderPickup() bool {
	if x != nil {
		return x.DoesSupportOrderPickup
	}
	return false
}

func (x *SimpleVendor) GetIsExpress() bool {
	if x != nil {
		return x.IsExpress
	}
	return false
}

type GetVendorByMultipleCoordinatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendors       []*SimpleVendor        `protobuf:"bytes,1,rep,name=vendors,proto3" json:"vendors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVendorByMultipleCoordinatesResponse) Reset() {
	*x = GetVendorByMultipleCoordinatesResponse{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendorByMultipleCoordinatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendorByMultipleCoordinatesResponse) ProtoMessage() {}

func (x *GetVendorByMultipleCoordinatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendorByMultipleCoordinatesResponse.ProtoReflect.Descriptor instead.
func (*GetVendorByMultipleCoordinatesResponse) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{17}
}

func (x *GetVendorByMultipleCoordinatesResponse) GetVendors() []*SimpleVendor {
	if x != nil {
		return x.Vendors
	}
	return nil
}

type GetEtaVendorsQuery struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Longitude              float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude               float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Vendors                []*VendorEtaQuery      `protobuf:"bytes,3,rep,name=vendors,proto3" json:"vendors,omitempty"`
	DontProcessDetail      bool                   `protobuf:"varint,4,opt,name=dont_process_detail,json=dontProcessDetail,proto3" json:"dont_process_detail,omitempty"`
	DontProcessExpectation bool                   `protobuf:"varint,5,opt,name=dont_process_expectation,json=dontProcessExpectation,proto3" json:"dont_process_expectation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetEtaVendorsQuery) Reset() {
	*x = GetEtaVendorsQuery{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtaVendorsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtaVendorsQuery) ProtoMessage() {}

func (x *GetEtaVendorsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtaVendorsQuery.ProtoReflect.Descriptor instead.
func (*GetEtaVendorsQuery) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{18}
}

func (x *GetEtaVendorsQuery) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetEtaVendorsQuery) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetEtaVendorsQuery) GetVendors() []*VendorEtaQuery {
	if x != nil {
		return x.Vendors
	}
	return nil
}

func (x *GetEtaVendorsQuery) GetDontProcessDetail() bool {
	if x != nil {
		return x.DontProcessDetail
	}
	return false
}

func (x *GetEtaVendorsQuery) GetDontProcessExpectation() bool {
	if x != nil {
		return x.DontProcessExpectation
	}
	return false
}

type VendorEtaQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorType    string                 `protobuf:"bytes,1,opt,name=vendor_type,json=vendorType,proto3" json:"vendor_type,omitempty"`
	VendorId      int64                  `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorEtaQuery) Reset() {
	*x = VendorEtaQuery{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorEtaQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorEtaQuery) ProtoMessage() {}

func (x *VendorEtaQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorEtaQuery.ProtoReflect.Descriptor instead.
func (*VendorEtaQuery) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{19}
}

func (x *VendorEtaQuery) GetVendorType() string {
	if x != nil {
		return x.VendorType
	}
	return ""
}

func (x *VendorEtaQuery) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

type GetEtaVendorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etas          []*DeliveryDetail      `protobuf:"bytes,1,rep,name=etas,proto3" json:"etas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEtaVendorsResponse) Reset() {
	*x = GetEtaVendorsResponse{}
	mi := &file_tmp_DruE8rlWKP_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtaVendorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtaVendorsResponse) ProtoMessage() {}

func (x *GetEtaVendorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_DruE8rlWKP_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtaVendorsResponse.ProtoReflect.Descriptor instead.
func (*GetEtaVendorsResponse) Descriptor() ([]byte, []int) {
	return file_tmp_DruE8rlWKP_rawDescGZIP(), []int{20}
}

func (x *GetEtaVendorsResponse) GetEtas() []*DeliveryDetail {
	if x != nil {
		return x.Etas
	}
	return nil
}

var File_tmp_DruE8rlWKP protoreflect.FileDescriptor

const file_tmp_DruE8rlWKP_rawDesc = "" +
	"\n" +
	"\x0etmp.DruE8rlWKP\x12\aservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x02\n" +
	"\x06Vendor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"is_express\x18\x02 \x01(\bR\tisExpress\x12!\n" +
	"\fdelivery_fee\x18\x03 \x01(\x03R\vdeliveryFee\x12!\n" +
	"\fdoes_deliver\x18\x04 \x01(\bR\vdoesDeliver\x12/\n" +
	"\x06detail\x18\x05 \x01(\v2\x17.service.DeliveryDetailR\x06detail\x12.\n" +
	"\x13minimum_order_value\x18\x06 \x01(\x03R\x11minimumOrderValue\x12'\n" +
	"\x0fdelivery_status\x18\a \x01(\tR\x0edeliveryStatus\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\x9f\x01\n" +
	"\x11OrderPickUpVendor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fdoes_deliver\x18\x02 \x01(\bR\vdoesDeliver\x12!\n" +
	"\fdelivery_fee\x18\x03 \x01(\x03R\vdeliveryFee\x124\n" +
	"\adetails\x18\x04 \x01(\v2\x1a.service.OrderPickupDetailR\adetails\"\xa0\x04\n" +
	"\x0eDeliveryDetail\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x03R\bvendorId\x126\n" +
	"\x17normal_preparation_time\x18\x02 \x01(\x03R\x15normalPreparationTime\x12,\n" +
	"\x12normal_time_factor\x18\x03 \x01(\x03R\x10normalTimeFactor\x12,\n" +
	"\x12safety_time_factor\x18\x04 \x01(\x03R\x10safetyTimeFactor\x12\x1d\n" +
	"\n" +
	"drive_time\x18\x05 \x01(\x03R\tdriveTime\x12=\n" +
	"\x1bmin_threshold_delivery_time\x18\x06 \x01(\x03R\x18minThresholdDeliveryTime\x12=\n" +
	"\x1bmax_threshold_delivery_time\x18\a \x01(\x03R\x18maxThresholdDeliveryTime\x12\x1d\n" +
	"\n" +
	"total_time\x18\b \x01(\x03R\ttotalTime\x12\x1d\n" +
	"\n" +
	"delay_time\x18\t \x01(\x03R\tdelayTime\x12\x1e\n" +
	"\vopen_at_eta\x18\n" +
	" \x01(\bR\topenAtEta\x12\x16\n" +
	"\x06action\x18\v \x01(\tR\x06action\x12$\n" +
	"\x0emax_total_time\x18\f \x01(\x03R\fmaxTotalTime\x12$\n" +
	"\x0emin_total_time\x18\r \x01(\x03R\fminTotalTime\"\x87\x01\n" +
	"\x11OrderPickupDetail\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x03R\bvendorId\x126\n" +
	"\x17normal_preparation_time\x18\x02 \x01(\x03R\x15normalPreparationTime\x12\x1d\n" +
	"\n" +
	"total_time\x18\b \x01(\x03R\ttotalTime\"\x87\x01\n" +
	"\x12GetAllVendorsQuery\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x127\n" +
	"\x18get_order_pickup_vendors\x18\x03 \x01(\bR\x15getOrderPickupVendors\"\x90\x01\n" +
	"\x15GetAllVendorsResponse\x12)\n" +
	"\avendors\x18\x01 \x03(\v2\x0f.service.VendorR\avendors\x12L\n" +
	"\x14order_pickup_vendors\x18\x02 \x03(\v2\x1a.service.OrderPickUpVendorR\x12orderPickupVendors\"\xc2\x02\n" +
	"\x14GetVendorsByIdsQuery\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1d\n" +
	"\n" +
	"vendor_ids\x18\x03 \x03(\x03R\tvendorIds\x12.\n" +
	"\x13dont_process_detail\x18\x04 \x01(\bR\x11dontProcessDetail\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x127\n" +
	"\x18get_order_pickup_vendors\x18\x06 \x01(\bR\x15getOrderPickupVendors\x128\n" +
	"\x18dont_process_expectation\x18\a \x01(\bR\x16dontProcessExpectation\"\x92\x01\n" +
	"\x17GetVendorsByIdsResponse\x12)\n" +
	"\avendors\x18\x01 \x03(\v2\x0f.service.VendorR\avendors\x12L\n" +
	"\x14order_pickup_vendors\x18\x02 \x03(\v2\x1a.service.OrderPickUpVendorR\x12orderPickupVendors\"\xf4\x01\n" +
	"%GetDeliveryEstimationTimeByOrderQuery\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x1b\n" +
	"\tvendor_id\x18\x04 \x01(\x03R\bvendorId\x12\x1f\n" +
	"\vvendor_type\x18\x05 \x01(\tR\n" +
	"vendorType\x128\n" +
	"\x18dont_process_expectation\x18\x06 \x01(\bR\x16dontProcessExpectation\"\xfd\x03\n" +
	"(GetDeliveryEstimationTimeByOrderResponse\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x03R\bvendorId\x126\n" +
	"\x17normal_preparation_time\x18\x02 \x01(\x03R\x15normalPreparationTime\x12,\n" +
	"\x12normal_time_factor\x18\x03 \x01(\x03R\x10normalTimeFactor\x12,\n" +
	"\x12safety_time_factor\x18\x04 \x01(\x03R\x10safetyTimeFactor\x12\x1f\n" +
	"\vbiker_found\x18\x05 \x01(\x03R\n" +
	"bikerFound\x12#\n" +
	"\rorders_around\x18\x06 \x01(\x03R\fordersAround\x12\x1d\n" +
	"\n" +
	"drive_time\x18\a \x01(\x03R\tdriveTime\x12-\n" +
	"\x12availability_index\x18\b \x01(\x02R\x11availabilityIndex\x12\x1d\n" +
	"\n" +
	"total_time\x18\t \x01(\x03R\ttotalTime\x12-\n" +
	"\x12basket_coefficient\x18\n" +
	" \x01(\x02R\x11basketCoefficient\x12\x1f\n" +
	"\vbasket_size\x18\v \x01(\x02R\n" +
	"basketSize\x12\x1d\n" +
	"\n" +
	"delay_time\x18\f \x01(\x03R\tdelayTime\"\x8e\x02\n" +
	"&GetDeliveryEstimationTimeByBasketQuery\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1b\n" +
	"\tvendor_id\x18\x03 \x01(\x03R\bvendorId\x12\x1f\n" +
	"\vvendor_type\x18\x04 \x01(\tR\n" +
	"vendorType\x122\n" +
	"\x15product_variation_ids\x18\x05 \x03(\x03R\x13productVariationIds\x128\n" +
	"\x18dont_process_expectation\x18\x06 \x01(\bR\x16dontProcessExpectation\"\xfe\x03\n" +
	")GetDeliveryEstimationTimeByBasketResponse\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x03R\bvendorId\x126\n" +
	"\x17normal_preparation_time\x18\x02 \x01(\x03R\x15normalPreparationTime\x12,\n" +
	"\x12normal_time_factor\x18\x03 \x01(\x03R\x10normalTimeFactor\x12,\n" +
	"\x12safety_time_factor\x18\x04 \x01(\x03R\x10safetyTimeFactor\x12\x1f\n" +
	"\vbiker_found\x18\x05 \x01(\x03R\n" +
	"bikerFound\x12#\n" +
	"\rorders_around\x18\x06 \x01(\x03R\fordersAround\x12\x1d\n" +
	"\n" +
	"drive_time\x18\a \x01(\x03R\tdriveTime\x12-\n" +
	"\x12availability_index\x18\b \x01(\x02R\x11availabilityIndex\x12\x1d\n" +
	"\n" +
	"total_time\x18\t \x01(\x03R\ttotalTime\x12-\n" +
	"\x12basket_coefficient\x18\n" +
	" \x01(\x02R\x11basketCoefficient\x12\x1f\n" +
	"\vbasket_size\x18\v \x01(\x02R\n" +
	"basketSize\x12\x1d\n" +
	"\n" +
	"delay_time\x18\f \x01(\x03R\tdelayTime\"V\n" +
	"\x1aGetOrderPickupVendorsQuery\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\"m\n" +
	"\x1dGetOrderPickupVendorsResponse\x12L\n" +
	"\x14order_pickup_vendors\x18\x01 \x03(\v2\x1a.service.OrderPickUpVendorR\x12orderPickupVendors\"F\n" +
	"\n" +
	"Coordinate\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\"\xa9\x01\n" +
	"#GetVendorByMultipleCoordinatesQuery\x125\n" +
	"\vcoordinates\x18\x01 \x03(\v2\x13.service.CoordinateR\vcoordinates\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\x03R\bvendorId\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\xbe\x01\n" +
	"\fSimpleVendor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fdoes_deliver\x18\x02 \x01(\bR\vdoesDeliver\x12!\n" +
	"\fdelivery_fee\x18\x03 \x01(\x03R\vdeliveryFee\x129\n" +
	"\x19does_support_order_pickup\x18\x04 \x01(\bR\x16doesSupportOrderPickup\x12\x1d\n" +
	"\n" +
	"is_express\x18\x05 \x01(\bR\tisExpress\"Y\n" +
	"&GetVendorByMultipleCoordinatesResponse\x12/\n" +
	"\avendors\x18\x01 \x03(\v2\x15.service.SimpleVendorR\avendors\"\xeb\x01\n" +
	"\x12GetEtaVendorsQuery\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x121\n" +
	"\avendors\x18\x03 \x03(\v2\x17.service.VendorEtaQueryR\avendors\x12.\n" +
	"\x13dont_process_detail\x18\x04 \x01(\bR\x11dontProcessDetail\x128\n" +
	"\x18dont_process_expectation\x18\x05 \x01(\bR\x16dontProcessExpectation\"N\n" +
	"\x0eVendorEtaQuery\x12\x1f\n" +
	"\vvendor_type\x18\x01 \x01(\tR\n" +
	"vendorType\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\x03R\bvendorId\"D\n" +
	"\x15GetEtaVendorsResponse\x12+\n" +
	"\x04etas\x18\x01 \x03(\v2\x17.service.DeliveryDetailR\x04etas2\x90\x06\n" +
	"\x15VendorDeliveryService\x12N\n" +
	"\rGetAllVendors\x12\x1b.service.GetAllVendorsQuery\x1a\x1e.service.GetAllVendorsResponse\"\x00\x12T\n" +
	"\x0fGetVendorsByIds\x12\x1d.service.GetVendorsByIdsQuery\x1a .service.GetVendorsByIdsResponse\"\x00\x12\x87\x01\n" +
	" GetDeliveryEstimationTimeByOrder\x12..service.GetDeliveryEstimationTimeByOrderQuery\x1a1.service.GetDeliveryEstimationTimeByOrderResponse\"\x00\x12\x8a\x01\n" +
	"!GetDeliveryEstimationTimeByBasket\x12/.service.GetDeliveryEstimationTimeByBasketQuery\x1a2.service.GetDeliveryEstimationTimeByBasketResponse\"\x00\x12f\n" +
	"\x15GetOrderPickupVendors\x12#.service.GetOrderPickupVendorsQuery\x1a&.service.GetOrderPickupVendorsResponse\"\x00\x12\x81\x01\n" +
	"\x1eGetVendorByMultipleCoordinates\x12,.service.GetVendorByMultipleCoordinatesQuery\x1a/.service.GetVendorByMultipleCoordinatesResponse\"\x00\x12N\n" +
	"\rGetEtaVendors\x12\x1b.service.GetEtaVendorsQuery\x1a\x1e.service.GetEtaVendorsResponse\"\x00B\bZ\x06./grpcb\x06proto3"

var (
	file_tmp_DruE8rlWKP_rawDescOnce sync.Once
	file_tmp_DruE8rlWKP_rawDescData []byte
)

func file_tmp_DruE8rlWKP_rawDescGZIP() []byte {
	file_tmp_DruE8rlWKP_rawDescOnce.Do(func() {
		file_tmp_DruE8rlWKP_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tmp_DruE8rlWKP_rawDesc), len(file_tmp_DruE8rlWKP_rawDesc)))
	})
	return file_tmp_DruE8rlWKP_rawDescData
}

var file_tmp_DruE8rlWKP_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_tmp_DruE8rlWKP_goTypes = []any{
	(*Vendor)(nil),                                    // 0: service.Vendor
	(*OrderPickUpVendor)(nil),                         // 1: service.OrderPickUpVendor
	(*DeliveryDetail)(nil),                            // 2: service.DeliveryDetail
	(*OrderPickupDetail)(nil),                         // 3: service.OrderPickupDetail
	(*GetAllVendorsQuery)(nil),                        // 4: service.GetAllVendorsQuery
	(*GetAllVendorsResponse)(nil),                     // 5: service.GetAllVendorsResponse
	(*GetVendorsByIdsQuery)(nil),                      // 6: service.GetVendorsByIdsQuery
	(*GetVendorsByIdsResponse)(nil),                   // 7: service.GetVendorsByIdsResponse
	(*GetDeliveryEstimationTimeByOrderQuery)(nil),     // 8: service.GetDeliveryEstimationTimeByOrderQuery
	(*GetDeliveryEstimationTimeByOrderResponse)(nil),  // 9: service.GetDeliveryEstimationTimeByOrderResponse
	(*GetDeliveryEstimationTimeByBasketQuery)(nil),    // 10: service.GetDeliveryEstimationTimeByBasketQuery
	(*GetDeliveryEstimationTimeByBasketResponse)(nil), // 11: service.GetDeliveryEstimationTimeByBasketResponse
	(*GetOrderPickupVendorsQuery)(nil),                // 12: service.GetOrderPickupVendorsQuery
	(*GetOrderPickupVendorsResponse)(nil),             // 13: service.GetOrderPickupVendorsResponse
	(*Coordinate)(nil),                                // 14: service.Coordinate
	(*GetVendorByMultipleCoordinatesQuery)(nil),       // 15: service.GetVendorByMultipleCoordinatesQuery
	(*SimpleVendor)(nil),                              // 16: service.SimpleVendor
	(*GetVendorByMultipleCoordinatesResponse)(nil),    // 17: service.GetVendorByMultipleCoordinatesResponse
	(*GetEtaVendorsQuery)(nil),                        // 18: service.GetEtaVendorsQuery
	(*VendorEtaQuery)(nil),                            // 19: service.VendorEtaQuery
	(*GetEtaVendorsResponse)(nil),                     // 20: service.GetEtaVendorsResponse
	(*timestamppb.Timestamp)(nil),                     // 21: google.protobuf.Timestamp
}
var file_tmp_DruE8rlWKP_depIdxs = []int32{
	2,  // 0: service.Vendor.detail:type_name -> service.DeliveryDetail
	3,  // 1: service.OrderPickUpVendor.details:type_name -> service.OrderPickupDetail
	0,  // 2: service.GetAllVendorsResponse.vendors:type_name -> service.Vendor
	1,  // 3: service.GetAllVendorsResponse.order_pickup_vendors:type_name -> service.OrderPickUpVendor
	21, // 4: service.GetVendorsByIdsQuery.time:type_name -> google.protobuf.Timestamp
	0,  // 5: service.GetVendorsByIdsResponse.vendors:type_name -> service.Vendor
	1,  // 6: service.GetVendorsByIdsResponse.order_pickup_vendors:type_name -> service.OrderPickUpVendor
	1,  // 7: service.GetOrderPickupVendorsResponse.order_pickup_vendors:type_name -> service.OrderPickUpVendor
	14, // 8: service.GetVendorByMultipleCoordinatesQuery.coordinates:type_name -> service.Coordinate
	21, // 9: service.GetVendorByMultipleCoordinatesQuery.time:type_name -> google.protobuf.Timestamp
	16, // 10: service.GetVendorByMultipleCoordinatesResponse.vendors:type_name -> service.SimpleVendor
	19, // 11: service.GetEtaVendorsQuery.vendors:type_name -> service.VendorEtaQuery
	2,  // 12: service.GetEtaVendorsResponse.etas:type_name -> service.DeliveryDetail
	4,  // 13: service.VendorDeliveryService.GetAllVendors:input_type -> service.GetAllVendorsQuery
	6,  // 14: service.VendorDeliveryService.GetVendorsByIds:input_type -> service.GetVendorsByIdsQuery
	8,  // 15: service.VendorDeliveryService.GetDeliveryEstimationTimeByOrder:input_type -> service.GetDeliveryEstimationTimeByOrderQuery
	10, // 16: service.VendorDeliveryService.GetDeliveryEstimationTimeByBasket:input_type -> service.GetDeliveryEstimationTimeByBasketQuery
	12, // 17: service.VendorDeliveryService.GetOrderPickupVendors:input_type -> service.GetOrderPickupVendorsQuery
	15, // 18: service.VendorDeliveryService.GetVendorByMultipleCoordinates:input_type -> service.GetVendorByMultipleCoordinatesQuery
	18, // 19: service.VendorDeliveryService.GetEtaVendors:input_type -> service.GetEtaVendorsQuery
	5,  // 20: service.VendorDeliveryService.GetAllVendors:output_type -> service.GetAllVendorsResponse
	7,  // 21: service.VendorDeliveryService.GetVendorsByIds:output_type -> service.GetVendorsByIdsResponse
	9,  // 22: service.VendorDeliveryService.GetDeliveryEstimationTimeByOrder:output_type -> service.GetDeliveryEstimationTimeByOrderResponse
	11, // 23: service.VendorDeliveryService.GetDeliveryEstimationTimeByBasket:output_type -> service.GetDeliveryEstimationTimeByBasketResponse
	13, // 24: service.VendorDeliveryService.GetOrderPickupVendors:output_type -> service.GetOrderPickupVendorsResponse
	17, // 25: service.VendorDeliveryService.GetVendorByMultipleCoordinates:output_type -> service.GetVendorByMultipleCoordinatesResponse
	20, // 26: service.VendorDeliveryService.GetEtaVendors:output_type -> service.GetEtaVendorsResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_tmp_DruE8rlWKP_init() }
func file_tmp_DruE8rlWKP_init() {
	if File_tmp_DruE8rlWKP != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tmp_DruE8rlWKP_rawDesc), len(file_tmp_DruE8rlWKP_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tmp_DruE8rlWKP_goTypes,
		DependencyIndexes: file_tmp_DruE8rlWKP_depIdxs,
		MessageInfos:      file_tmp_DruE8rlWKP_msgTypes,
	}.Build()
	File_tmp_DruE8rlWKP = out.File
	file_tmp_DruE8rlWKP_goTypes = nil
	file_tmp_DruE8rlWKP_depIdxs = nil
}
