// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tmp.MhZyXfeTib

//import "google/protobuf/wrappers.proto";

package svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserLatitude      float64                `protobuf:"fixed64,1,opt,name=UserLatitude,proto3" json:"UserLatitude,omitempty"`
	UserLongitude     float64                `protobuf:"fixed64,2,opt,name=UserLongitude,proto3" json:"UserLongitude,omitempty"`
	UserSessionID     string                 `protobuf:"bytes,3,opt,name=UserSessionID,proto3" json:"UserSessionID,omitempty"`
	VendorSuperTypeID uint64                 `protobuf:"varint,4,opt,name=VendorSuperTypeID,proto3" json:"VendorSuperTypeID,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_tmp_MhZyXfeTib_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_MhZyXfeTib_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_tmp_MhZyXfeTib_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetUserLatitude() float64 {
	if x != nil {
		return x.UserLatitude
	}
	return 0
}

func (x *ListRequest) GetUserLongitude() float64 {
	if x != nil {
		return x.UserLongitude
	}
	return 0
}

func (x *ListRequest) GetUserSessionID() string {
	if x != nil {
		return x.UserSessionID
	}
	return ""
}

func (x *ListRequest) GetVendorSuperTypeID() uint64 {
	if x != nil {
		return x.VendorSuperTypeID
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reels         []*Reel                `protobuf:"bytes,100,rep,name=Reels,proto3" json:"Reels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_tmp_MhZyXfeTib_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_MhZyXfeTib_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_tmp_MhZyXfeTib_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetReels() []*Reel {
	if x != nil {
		return x.Reels
	}
	return nil
}

type Reel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorID      uint32                 `protobuf:"varint,1,opt,name=VendorID,proto3" json:"VendorID,omitempty"`
	Stories       []*Stories             `protobuf:"bytes,10,rep,name=Stories,proto3" json:"Stories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reel) Reset() {
	*x = Reel{}
	mi := &file_tmp_MhZyXfeTib_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reel) ProtoMessage() {}

func (x *Reel) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_MhZyXfeTib_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reel.ProtoReflect.Descriptor instead.
func (*Reel) Descriptor() ([]byte, []int) {
	return file_tmp_MhZyXfeTib_rawDescGZIP(), []int{2}
}

func (x *Reel) GetVendorID() uint32 {
	if x != nil {
		return x.VendorID
	}
	return 0
}

func (x *Reel) GetStories() []*Stories {
	if x != nil {
		return x.Stories
	}
	return nil
}

type Stories struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	VendorID   uint32                 `protobuf:"varint,1,opt,name=VendorID,proto3" json:"VendorID,omitempty"`
	ContentUrl string                 `protobuf:"bytes,2,opt,name=ContentUrl,proto3" json:"ContentUrl,omitempty"`
	FileFormat string                 `protobuf:"bytes,3,opt,name=FileFormat,proto3" json:"FileFormat,omitempty"`
	// google.protobuf.StringValue PublishDate = 4;
	PublishDate   string `protobuf:"bytes,4,opt,name=PublishDate,proto3" json:"PublishDate,omitempty"`
	StoryHash     string `protobuf:"bytes,10,opt,name=StoryHash,proto3" json:"StoryHash,omitempty"`
	Seen          bool   `protobuf:"varint,11,opt,name=Seen,proto3" json:"Seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stories) Reset() {
	*x = Stories{}
	mi := &file_tmp_MhZyXfeTib_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stories) ProtoMessage() {}

func (x *Stories) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_MhZyXfeTib_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stories.ProtoReflect.Descriptor instead.
func (*Stories) Descriptor() ([]byte, []int) {
	return file_tmp_MhZyXfeTib_rawDescGZIP(), []int{3}
}

func (x *Stories) GetVendorID() uint32 {
	if x != nil {
		return x.VendorID
	}
	return 0
}

func (x *Stories) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *Stories) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

func (x *Stories) GetPublishDate() string {
	if x != nil {
		return x.PublishDate
	}
	return ""
}

func (x *Stories) GetStoryHash() string {
	if x != nil {
		return x.StoryHash
	}
	return ""
}

func (x *Stories) GetSeen() bool {
	if x != nil {
		return x.Seen
	}
	return false
}

var File_tmp_MhZyXfeTib protoreflect.FileDescriptor

const file_tmp_MhZyXfeTib_rawDesc = "" +
	"\n" +
	"\x0etmp.MhZyXfeTib\x12\aservice\"\xab\x01\n" +
	"\vListRequest\x12\"\n" +
	"\fUserLatitude\x18\x01 \x01(\x01R\fUserLatitude\x12$\n" +
	"\rUserLongitude\x18\x02 \x01(\x01R\rUserLongitude\x12$\n" +
	"\rUserSessionID\x18\x03 \x01(\tR\rUserSessionID\x12,\n" +
	"\x11VendorSuperTypeID\x18\x04 \x01(\x04R\x11VendorSuperTypeID\"3\n" +
	"\fListResponse\x12#\n" +
	"\x05Reels\x18d \x03(\v2\r.service.ReelR\x05Reels\"N\n" +
	"\x04Reel\x12\x1a\n" +
	"\bVendorID\x18\x01 \x01(\rR\bVendorID\x12*\n" +
	"\aStories\x18\n" +
	" \x03(\v2\x10.service.StoriesR\aStories\"\xb9\x01\n" +
	"\aStories\x12\x1a\n" +
	"\bVendorID\x18\x01 \x01(\rR\bVendorID\x12\x1e\n" +
	"\n" +
	"ContentUrl\x18\x02 \x01(\tR\n" +
	"ContentUrl\x12\x1e\n" +
	"\n" +
	"FileFormat\x18\x03 \x01(\tR\n" +
	"FileFormat\x12 \n" +
	"\vPublishDate\x18\x04 \x01(\tR\vPublishDate\x12\x1c\n" +
	"\tStoryHash\x18\n" +
	" \x01(\tR\tStoryHash\x12\x12\n" +
	"\x04Seen\x18\v \x01(\bR\x04Seen2C\n" +
	"\fStoryService\x123\n" +
	"\x04List\x12\x14.service.ListRequest\x1a\x15.service.ListResponseB\aZ\x05.;svcb\x06proto3"

var (
	file_tmp_MhZyXfeTib_rawDescOnce sync.Once
	file_tmp_MhZyXfeTib_rawDescData []byte
)

func file_tmp_MhZyXfeTib_rawDescGZIP() []byte {
	file_tmp_MhZyXfeTib_rawDescOnce.Do(func() {
		file_tmp_MhZyXfeTib_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tmp_MhZyXfeTib_rawDesc), len(file_tmp_MhZyXfeTib_rawDesc)))
	})
	return file_tmp_MhZyXfeTib_rawDescData
}

var file_tmp_MhZyXfeTib_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tmp_MhZyXfeTib_goTypes = []any{
	(*ListRequest)(nil),  // 0: service.ListRequest
	(*ListResponse)(nil), // 1: service.ListResponse
	(*Reel)(nil),         // 2: service.Reel
	(*Stories)(nil),      // 3: service.Stories
}
var file_tmp_MhZyXfeTib_depIdxs = []int32{
	2, // 0: service.ListResponse.Reels:type_name -> service.Reel
	3, // 1: service.Reel.Stories:type_name -> service.Stories
	0, // 2: service.StoryService.List:input_type -> service.ListRequest
	1, // 3: service.StoryService.List:output_type -> service.ListResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tmp_MhZyXfeTib_init() }
func file_tmp_MhZyXfeTib_init() {
	if File_tmp_MhZyXfeTib != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tmp_MhZyXfeTib_rawDesc), len(file_tmp_MhZyXfeTib_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tmp_MhZyXfeTib_goTypes,
		DependencyIndexes: file_tmp_MhZyXfeTib_depIdxs,
		MessageInfos:      file_tmp_MhZyXfeTib_msgTypes,
	}.Build()
	File_tmp_MhZyXfeTib = out.File
	file_tmp_MhZyXfeTib_goTypes = nil
	file_tmp_MhZyXfeTib_depIdxs = nil
}
